-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3Q+Tx/OgcwaTbqPG
xTSUUTE6TosbsPEHxR7LU82VJO+gCgYIKoZIzj0DAQehRANCAATsZTXAdjugGMtI
pi5voMQ7lMqJyViej0B6pnTT/ZC2Zm7B+ZriTR72pP1JxJsqDnDG+fc4XItSGW9c
MhEE+tKL
-----END PRIVATE KEY-----